name: Build Samsung Galaxy S10 5G (LineageOS A16 + KernelSU-Next + SUSFS)

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "samsung_s10_5g"
  DEVICE_CODENAME : "beyondx"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LLVM=1 LLVM_IAS=1"

  KERNEL_SOURCE : "https://github.com/ravindu644/android_kernel_aosp_exynos9820.git"
  KERNEL_BRANCH : "lineage-22.1"

  CLANG_SOURCE : "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman"
  CLANG_BRANCH : ""

  GCC_GNU : false
  GCC_64_SOURCE : ""
  GCC_64_BRANCH : ""
  GCC_32_SOURCE : ""
  GCC_32_BRANCH : ""

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "exynos9820_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : ""
  KERNELSU_BRANCH : ""

  KERNELSU_AUTO_GET : "true"
  KERNELSU_AUTO_FORK : "next" # xxksu, rsuntk, next, resukisu and sukisu

  SUSFS_ENABLE : true
  SUSFS_FIXED : false

  AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH : "master"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "lineageos22_a16"

  # Other env
  PYTHON_VERSION: "3"

  PACK_METHOD: "Anykernel3"
  PACK_KMODULES: "false"

  KERNELSU_METHOD: "shell"

  PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches"
  PATCHES_BRANCH: "samsung_kernel"

  SUSFS_FOLDER_FIXED: ""
  SUSFS_PATCH_FIXED: ""

  REKERNEL_ENABLE: "false"
  DROIDSPACES_ENABLE: "false"
  NOMOUNT_ENABLE: "false"

  HOOK_METHOD: "syscall"
  KERNEL_PATCH: "false"

  KPM_ENABLE: "false"
  KPM_INLINE: "false"

  BASEBAND_GUARD_ENABLE: "false"
  BASEBAND_GUARD_BOOT: "false"

  GENERATE_DTB: "false"
  GENERATE_CHIP: "exynos"

  BUILD_DEBUGGER: "false"
  SKIP_PATCH: "false"

  BUILD_OTHER_CONFIG: "false"
  MERGE_CONFIG_FILES: ""

  FREE_MORE_SPACE: "false"

jobs:
  build-kernel:
    name: Samsung S10 5G (LineageOS A16)
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v4

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get neccssary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 📦 Pack AnyKernel3 Process
        uses: ./.github/workflows/pack-process

      - name: 📤 Upload Build Artifacts
        uses: ./.github/workflows/upload-files
